### ISSUE TITLE
distance analysis type output for (a) fixed distance(s)

### ISSUE THREAD

**Issue by hansvancalster** [STBrinkmann/GVI#2]
Hi! Great package!
I wonder if it would be possible for you to allow `GVI::distance_analysis()` to only output results for a specific distance instead of all distances from `1:max_distance`.
My use case is that I would like to calculate `visibility` (proportion of visible cells to all cells inside a buffer distance) at a specific distance for a large number of points. Perhaps allow the user to pass a vector of distance values at which visibility and other measures need to be calculated?

**Comment by STBrinkmann** [comment]
Hi, thanks for the feedback!

Great idea, I'll include this functionality soon.

However, I need to clarify the `GVI::distance_analysis()` function. It's currently being used in a ongoing research project and therefore still under heavy developement and lacks examples.

For example `visibility` at 800 m only represents the proportion of visible cells to all cells with a distance of 800 m **specifically**! This allows analysing visibility metrics at distance specific thresholds. E.g. how much greenspace is visible at 10 m distance from the observer location?

`GVI::vgvi_from_sf()` on the other hand derives a Greenness Visibility Index for the complete viewshed.

It sounds like you were interested in a function that calculates the overall proportion of visible cells to all cells inside a buffer distance.
For that I have build a small function `visibility_proportion`:

    # Download DEM
    DEM_tmp <- tempfile(fileext = ".tif")
    download.file(url = "https://github.com/STBrinkmann/data/raw/main/GVI_Data/GVI_DEM.tif",
                  destfile = DEM_tmp, mode="wb")
    
    # Download DSM
    DSM_tmp <- tempfile(fileext = ".tif")
    download.file(url = "https://github.com/STBrinkmann/data/raw/main/GVI_Data/GVI_DSM.tif",
                  destfile = DSM_tmp, mode="wb")
    
    
    # Load libraries. if one is not installed, use the "install.packages()" function
    library(terra)
    library(sf)
    library(sfheaders)
    
    # Load raster objects
    DEM <- rast(DEM_tmp)
    DSM <- rast(DSM_tmp)
    
    # Generate single observer point
    observer <- st_sf(sf_point(c(492243.3, 5454231.4)), crs = st_crs(26910))
    
    library(GVI)
    visibility_proportion(observer = observer, dsm_rast = DSM, dtm_rast = DEM,
                          max_distance = 200, observer_height = 1.7, plot = TRUE)

**Comment by hansvancalster** [comment]
Thank you! I'm sure that will work as I had a similar function based on `viewshed()` written in my workflow. Thank you also for the explanation about `distance_analysis()`, because I had indeed misunderstood what the function does.

I tried installing the new version of the package, but it currently fails due to:

```
Error: package or namespace load failed for 'GVI' in namespaceExport(ns, exports):
 undefined exports: vgvi_test
```

**Comment by hansvancalster** [comment]
I made a fork of the repo and the installation error can be solved by running `devtools::document()` twice. If you want, I can make a PR.

**Comment by STBrinkmann** [comment]
Thanks for reporting the bug from NAMESPACE. I've just fixed it.

About your use case:
It sounds like you need to calculate the visible proportion of a viewshed for many observer locations.
I could work on the `visibility_proportion` function so that it supports the input of multiple locations and enable multi-threading. The function would then return the proportion of visible area for each observer.
That would help you with large scale analysis.

I'm a little busy right now, but if it sounds helpful to you, I could implement it once I'm free in a couple of weeks.

**Comment by hansvancalster** [comment]
> About your use case: It sounds like you need to calculate the visible proportion of a viewshed for many observer locations. I could work on the `visibility_proportion` function so that it supports the input of multiple locations and enable multi-threading. The function would then return the proportion of visible area for each observer. That would help you with large scale analysis.
> 
> I'm a little busy right now, but if it sounds helpful to you, I could implement it once I'm free in a couple of weeks.

That would be awesome! It would definitely help speeding up things. My current workflow is relatively slow and processes at a little under one point per second (300 m distance; 1 m resolution) - although the bottleneck is currently mostly due to getting DTM/DSM data from a WCS web coverage service (we also have the DTM/DSM files at a network drive, but the network IO is slower than using the WCS per point). If I could use the DTM / DSM tif files locally and/or do the calculations in batches, things would look better and with multi-threading even better.  It's not urgent for me too - I'm only prototyping now and the real case where many points need to be processed will only be in a couple of months.

**Comment by hansvancalster** [comment]
I've given this some more thought and I think what would be very useful is a function that basically has the same arguments as `GVI::vgvi_from_sf()` (excepting `greenspace_rast`), but instead of returning the VGVI for each point have it return the `visibility_proportion` for each point (possibly weighted - I noticed an unweighted version is possible by setting `m = 0, b = 0, mode = "exponential"`).
I especially like the possibility we then have to pass (1) multiple points, (2) lines or polygons (which get translated to points). I think this will be a very useful feature for many use cases.

**Comment by STBrinkmann** [comment]
Great suggestions! I also think it should be as close as possible to the `vgvi_from_sf` function (except `greenspace_rast`) and support multiple geometry types (points, lines, polygons). This should also solve your bottleneck due to getting DSM/DEM data from the web as it needed to be downloaded only once for all points!
I've also decided to implement the `visibility_proportion` function in C++ using OpenMP for parallel CPU computation.

**Comment by hansvancalster** [comment]
Another possibility is to have `vgvi_from_sf()` return `vgvi` **and** `visibility_proportion` for each point. Both indices have their own use cases / interpretation. The product of `visibility_proportion` and `vgvi` is also useful as an overall index of visible green. For instance, a `vgvi `of 0.5 with a corresponding `visibility_proportion `of 1 is something totally different compared to a `vgvi` of 0.5 and a `visibility_proportion` of 0.1. Another example, a viewshed where everything is visible but only 1/4 of it is green could be considered similar to a viewshed where half of the pixels are visible, of which half of them are green (1 x 0.25 = 0.5 x 0.5 = 0.25). Having both indices together could help with interpretation.

**Comment by hansvancalster** [comment]
> Great suggestions! I also think it should be as close as possible to the `vgvi_from_sf` function (except `greenspace_rast`) and support multiple geometry types (points, lines, polygons). This should also solve your bottleneck due to getting DSM/DEM data from the web as it needed to be downloaded only once for all points! I've also decided to implement the `visibility_proportion` function in C++ using OpenMP for parallel CPU computation.

Hi! I'm just wondering if you already had time to work on these features? It would be very useful for my work. Let me know if there is anything I can do.

**Comment by STBrinkmann** [comment]
Hi. My apologies for the late answer, I was busy with work/university. I am currently considering how to implement the function with a weighting option into the `vgvi_from_sf` function. I think I should make some progress next week.

**Comment by hansvancalster** [comment]
Hi, did you happen to make progress on this issue? I would be glad to test this feature (or help out in any other way you think is relevant).

**Comment by hansvancalster** [comment]
Thank you for merging #4 ! I will close this issue as completed.
