### ISSUE TITLE
Using another coordinate system

### ISSUE THREAD

**Issue by Tobias1234** [STBrinkmann/GVI#3]
Hi,
Thanks for a great R script!
I am trying to use code below. But R studio crashes. Any input why?

```
# Load libraries. if one is not installed, use the "install.packages()" function
library(terra)
library(sf)
library(sfheaders)

# Load raster objects
DEM <- rast("C:/dtm.tif")
DSM <- rast("C:/dsm.tif")
GreenSpace <- rast("C:/raster_tree.tif")


# Generate single observer point
observer <- st_sf(sf_point(c(116655.0, 6400000.0)), crs = st_crs(3008))

library(GVI)
vs <- viewshed(observer = observer, dsm_rast = DSM, dtm_rast = DEM,
               max_distance = 50, observer_height = 1.7, plot = TRUE)
```
Best regards, Tobias

**Comment by STBrinkmann** [comment]
Hi Tobias,
can you tell me if an error message is returned or does R Studio simply crash?

**Comment by Tobias1234** [comment]
Hi Sebastian,
Simply crashes. I attached my data also if it can be of any help. I can plot data so it seems ok. 
It seems to crashes when I run the last code ```
library(GVI)
vs <- viewshed(observer = observer, dsm_rast = DSM, dtm_rast = DEM,
               max_distance = 50, observer_height = 1.7, plot = TRUE)
```
[data.zip](https://github.com/STBrinkmann/GVI/files/8561941/data.zip)
s

**Comment by STBrinkmann** [comment]
It should be working now, please install the latest version.
It was a rare case that I haven't encountered so far. So thanks for reporting this bug!

Can you quickly report back if it worked for you?

**Comment by Tobias1234** [comment]
Hi again,
Code works but plots looks strange. 
![image](https://user-images.githubusercontent.com/7010225/165315905-18421ab2-1daa-47c7-b517-2d299254a6ed.png)

**Comment by STBrinkmann** [comment]
Hmm plots look strange indeed.
When I run the code on the data you have provided, it looks fine.

Sometimes I have issues with updating packages using `remotes::install_git()` on windows. It helps to remove the folder of the package manually, and then run `remotes::install_git()`.

    remotes::install_git("https://github.com/STBrinkmann/GVI")
    
    # Load libraries. if one is not installed, use the "install.packages()" function
    library(terra)
    library(sf)
    library(sfheaders)
    
    setwd("data/")
    
    # Load raster objects
    DEM <- rast("dtm.tif")
    DSM <- rast("dsm.tif")
    
    # Generate single observer point
    observer <- st_sf(sf_point(c(116655.0, 6400000.0)), crs = st_crs(3008))
    
    library(GVI)
    vs <- viewshed(observer = observer, dsm_rast = DSM, dtm_rast = DEM,
                   max_distance = 50, observer_height = 1.7, plot = TRUE)

![grafik](https://user-images.githubusercontent.com/20467280/165335090-b4dbc21f-efa9-4f23-8e66-0d5b1ee15179.png)

I've tested it on Ubuntu with the same results.

Can you try by manualy removing GVI from your R-Library folder (e.g. _C:\Users\Sebastian\Documents\R\win-library\4.0\GVI_) and than install the package again?

**Comment by Tobias1234** [comment]
Sorry for late answer (busy meeting days). It works now the error was on my side. Thanks for your help!
