### ISSUE TITLE
multiple cores and Windows

### ISSUE THREAD

**Issue by hansvancalster** [STBrinkmann/GVI#5]
While working on #4, I have noticed that setting argument `cores` > 1 in `vvi_from_sf()` on a Windows machine is not working. In debugging mode I noticed that repeated execution of the same call to `vvi.cpp` gives different results (sometimes the correct result, but unpredictably it is a wrong result). Setting `cores = 1` does not have this issue.

I only tested this on Windows, but I suspect it might be a Windows specific issue with the OpenMP plugin.

I suspect this will also affect `vgvi_from_sf()` (`vvi_from_sf()` is only available in #4).

**Comment by STBrinkmann** [comment]
Hello @hansvancalster  would you be so kind to check if this is still the case in the new [CGEI](https://github.com/STBrinkmann/CGEI) R package? I have just tested it locally on Windows 10 and Ubuntu. Both benefited from `cores` > 1. It would help me if you could open a new issue in CGEI. Thanks!
