### ISSUE TITLE
Calling && or || with either argument of length greater than one gives error in `visualiseWeights()`

### ISSUE THREAD

**Issue by wlangera** [STBrinkmann/GVI#8]
`visualiseWeights()` does not longer work properly under R 4.3.0

Changes in R 4.2.0
Calling && or || with either argument of length greater than one now gives a warning (which it is intended will become an error).

Changes in R 4.3.0
Calling && or || with LHS or (if evaluated) RHS of length greater than one is now always an error, with a report of the form

I have created a pull request to fix this #7 
Two options are possible:

```
identical(mode, c("logit", "exponential"))
all(mode == c("logit", "exponential"))
```

Kind regards,
Ward

**Comment by STBrinkmann** [comment]
Thanks, I adjusted the fix in the new [CGEI](https://github.com/STBrinkmann/CGEI) R package, which supports all the current GVI functions.
